import type { Metadata } from "next";
import "./globals.css";
import StarsCanvas from '../Components/StarBackground'
import Navbar from "@/Components/Navbar";
import { Cinzel, Inter } from "next/font/google";
import GalaxyCursor from "@/Components/GalaxyCursor";

export const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  display: "swap",
  variable: "--font-cinzel", // 👈 important
});

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // 👈 important
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`relative ${cinzel.variable}
    ${inter.variable}  bg-[rgba(3,0,21,0.3)] `}>
        <StarsCanvas />
        <Navbar/>
        {/* <GalaxyCursor/> */}
        <main className=" z-100">
          {children}
        </main>

      </body>
    </html>
  );
}
