import type { Metadata } from "next";
import "./globals.css";
import StarsCanvas from '../Components/StarBackground'
import Navbar from "@/Components/Navbar";
import { Cinzel, Inter } from "next/font/google";

export const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  display: "swap",
  variable: "--font-cinzel", // 👈 important
});

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // 👈 important
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${cinzel.variable}`}  
      > 
        <StarsCanvas />
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
